site :opscode

#
# Notes:
#   * never add docker deployment tooling, only intallation of docker/lxc runtimes
#

cookbook 'apt'
cookbook 'git'
cookbook 'dmg', git: "https://github.com/JasonGiedymin/dmg.git", branch: "dev/symbol_keys"
cookbook 'dpkg_autostart', git: 'https://github.com/hw-cookbooks/dpkg_autostart'
cookbook 'build-essential'

cookbook 'lxc', git: "https://github.com/hw-cookbooks/lxc.git"
cookbook 'docker', git: 'https://github.com/bflad/chef-docker.git'
cookbook 'etcd', git: 'https://github.com/spheromak/etcd-cookbook.git'
cookbook 'mesos', git: 'https://github.com/everpeace/cookbook-mesos.git'

cookbook 'chef-server', git: "https://github.com/JasonGiedymin/chef-server.git", branch: "fix/cache_dir_missing"
cookbook 'chef-client'

cookbook 'rvm', git: "https://github.com/fnichol/chef-rvm.git"
cookbook 'ruby_build'
cookbook 'java'
cookbook 'maven'
cookbook 'scala'
cookbook 'golang', git: 'https://github.com/NOX73/chef-golang.git'
cookbook 'python'
cookbook 'nodejs'

cookbook 'mysql'
cookbook 'nginx'
cookbook 'jenkins'
cookbook 'bind'
cookbook 'bind9'
cookbook 'bind9-chroot', git: "https://github.com/tnarik/chef-cookbook_bind9-chroot.git", tag: "0.4.1"
